wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1645663121
    t:
      1:
      - 5
      2:
      - 5
      4: 3.9.10
      5: 0.12.3
      8:
      - 5
