wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1645581404
    t:
      4: 3.9.10
      5: 0.12.3
      8:
      - 5
