wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1645568925
    t:
      3:
      - 2
      4: 3.10.2
      5: 0.12.3
      8:
      - 5
